[[main]]
none = "none"

[[main]]
name = "Snippets"
pre = "code"
pageRef = "snippets"
identifier = "jUx3ewCfsR"
weight = 1

[[main]]
name = "Music"
pre = "music"
pageRef = "music"
identifier = "sXF5qwqMFv"
weight = 3

[[main]]
name = "Projects"
pre = "codepen"
pageRef = "/projects"
identifier = "Jrdjo89eco"
weight = 2

[[footer]]
none = "none"

[[footer]]
name = "Tags"
pageRef = "/tags"
identifier = "rELlHvO2GD"
weight = 9999
